version: "1.0"
services:
    mysql-import:
        image: mysql:8.3.0
        ports: "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volume:
            - ./mysql:/var/lib/mysql
        
    